#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# iTerm2 shell integration
# source ~/.iterm2_shell_integration.zsh

# text editor
export EDITOR=bbedit

# path
export PATH=/Applications/Postgres.app/Contents/Versions/latest/bin:$PATH
export PATH=/usr/local/share/npm/bin:$PATH
export PATH=~/.rbenv/shims:$PATH
export PATH=~/Applications/anaconda3/bin:$PATH
export PATH=/usr/local/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/opt/apr/bin:$PATH

# enable rbenv shims
eval "$(rbenv init -)"

# pharmgkb paths
export PHARMGKB=~/pharmgkb/PharmGKB
export PHARMGKB_USER=whaleyr
export PHARMGKB_TOOLS=~/pharmgkb/tools
export PHARMGKB_WEB=~/pharmgkb/pgkb-web-site
export PSB_BASE=~/pharmgkb/PSB

# java app paths
export JAVA_HOME=/Library/Java/JavaVirtualMachines/Current/Contents/Home
export CATALINA_HOME=$PHARMGKB_TOOLS/tomcat
export CATALINA_BASE=$PHARMGKB/runtime
export ANT_HOME=/usr/local/opt/ant/libexec
export ANT_OPTS=-Xmx768M

# for ansible
export ANSIBLE=/usr/local/lib/python2.7/site-packages/ansible
export ANSIBLE_INVENTORY=$HOME/pharmgkb/league-servers/ansible/hosts.ini
export PYTHONPATH=/usr/local/bin/python
export ANSIBLE_LIBRARY=${ANSIBLE}/library
export ANSIBLE_VAULT_PASSWORD_FILE=${HOME}/.vault_pass.txt

# for homebrew, wait some time before doing another auto update
export HOMEBREW_AUTO_UPDATE_SECS=3600

# aliases
alias git='/usr/local/bin/git'
alias smi='cd $PHARMGKB'
alias web='cd $PHARMGKB_WEB'
alias psb='cd $PSB_BASE'
alias luke='java -jar ~/pharmgkb/tools/lukeall-3.5.0.jar'
alias league='cd ~/pharmgkb/league-servers'
alias logdir='open $PHARMGKB/runtime/site/logs/'
alias datadir='open $PHARMGKB/../data/common/'
alias minecraft='java -d64 -Xmx4g -jar $HOME/Applications/Minecraft/Minecraft.jar'
alias ans='cd ~/pharmgkb/league-servers/ansible'
# alias python='python3'
alias monstat='echo "Should see 4 processes" && ssh es "fileStat && cnStat && esStat && vfStat"'
